# -*- coding: utf-8 -*-
"""demographic_data_analyzer.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/helioluciano620-bit/2f57b73c8b909896b73005a49d7b6cd1/projecto1.ipynb

# Conheça o Colab
"""

import pandas as pd

def calculate_demographic_data(print_data=True):
    df = pd.read_csv('https://raw.githubusercontent.com/freeCodeCamp/boilerplate-demographic-data-analyzer/main/adult.data.csv')

    # 1. Contagem por raça
    race_count = df['race'].value_counts()

    # 2. Idade média dos homens
    average_age_men = round(df[df['sex'] == 'Male']['age'].mean(), 1)

    # 3. Porcentagem com bacharelado
    percentage_bachelors = round(
        (df['education'] == 'Bachelors').sum() / len(df) * 100, 1
    )

    # 4. Educação avançada e salário > 50K
    advanced = df['education'].isin(['Bachelors', 'Masters', 'Doctorate'])
    higher_education_rich = round(
        (df[advanced]['salary'] == '>50K').sum() / advanced.sum() * 100, 1
    )

    # 5. Sem educação superior e salário > 50K
    lower_education_rich = round(
        (df[~advanced]['salary'] == '>50K').sum() / (~advanced).sum() * 100, 1
    )

    # 6. Mínimo de horas trabalhadas por semana
    min_work_hours = df['hours-per-week'].min()

    # 7. Porcentagem dos que trabalham mínimo de horas e ganham > 50K
    min_workers = df[df['hours-per-week'] == min_work_hours]
    rich_percentage = round(
        (min_workers['salary'] == '>50K').sum() / len(min_workers) * 100, 1
    )

    # 8. País com maior porcentagem de pessoas que ganham > 50K
    country_rich = (
        df[df['salary'] == '>50K']['native-country'].value_counts() /
        df['native-country'].value_counts() * 100
    )
    highest_earning_country = country_rich.idxmax()
    highest_earning_country_percentage = round(country_rich.max(), 1)

    # 9. Ocupação mais popular entre os que ganham > 50K na Índia
    top_IN_occupation = (
        df[(df['native-country'] == 'India') & (df['salary'] == '>50K')]
        ['occupation'].value_counts().idxmax()
    )

    if print_data:
        print("Contagem por raça:\n", race_count)
        print("Idade média dos homens:", average_age_men)
        print("% com Bacharelado:", percentage_bachelors)
        print("% educação avançada com >50K:", higher_education_rich)
        print("% sem educação superior com >50K:", lower_education_rich)
        print("Mínimo de horas/semana:", min_work_hours)
        print("% que trabalham mínimo e ganham >50K:", rich_percentage)
        print("País com maior % >50K:", highest_earning_country)
        print("Porcentagem:", highest_earning_country_percentage)
        print("Ocupação top na Índia (>50K):", top_IN_occupation)

    return {
        'race_count': race_count,
        'average_age_men': average_age_men,
        'percentage_bachelors': percentage_bachelors,
        'higher_education_rich': higher_education_rich,
        'lower_education_rich': lower_education_rich,
        'min_work_hours': min_work_hours,
        'rich_percentage': rich_percentage,
        'highest_earning_country': highest_earning_country,
        'highest_earning_country_percentage': highest_earning_country_percentage,
        'top_IN_occupation': top_IN_occupation,
    }

calculate_demographic_data()